name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      # Bump version
      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}
      # Push changes to main branch
      - name: Push changes
        run: git push -u origin main
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
