name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup git config
        run: |
          git config --global user.email "ghdtjrald240@gmail.com"
          git config --global user.name "Seokmin (GitHub Actions)"
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      # Bump version
      - name: Bump version
        id: version
        shell: bash
        run: |
          version=$(npm version ${{ github.event.inputs.version }} -m "Bump version to %s")
          echo "version=${version}" >> $GITHUB_OUTPUT
      # Push changes to main branch
      - name: Push changes
        run: git push -u origin main --follow-tags
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Create a release
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
